external_components:
  - source: github://gelidusresearch/esphome-secplus-gdo
    components: [ secplus_gdo ]
    refresh: 0s

substitutions:
  id_prefix: grgdo1
  friendly_name: "GRGDO1"
  uart_tx_pin: GPIO22           # J4 Pin 1 or 3 Red CTRL
  uart_rx_pin: GPIO21           # J4 Pin 1 or 3 Red CTRL
  input_obst_pin: GPIO23        # J4 Pin 4 Grey OBST - not required with secplus_gdo
  dry_contact_open_pin: GPIO17  # J4 Pin 6 Green
  dry_contact_close_pin: GPIO19 # J4 Pin 7 Blue
  dry_contact_light_pin: GPIO18 # J4 Pin 8 Orange
  garage_door_cover_name: Garage Door
  garage_light_name: Garage Light
  garage_openings_name: Garage Openings
  garage_lock_name: Lock
  garage_motion_name: Motion
  garage_obstruction_name: Obstruction
  garage_motor_name: Motor
  garage_button_name: Wall Button
  garage_sync_name: Synced

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  baud_rate: 921600
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "PUT YOUR KEY HERE"

ota:
  - platform: esphome


esphome:
  name:  ${id_prefix}
  friendly_name: ${friendly_name}
  comment: "ESP32: Garage Door Opener"
  platformio_options:
    build_flags:
      - -Wl,--wrap=esp_panic_handler

wifi:
  on_connect:
    lambda: id(${id_prefix}).start_gdo();
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "grgdo1"
    password: ""
    ap_timeout: 15s

captive_portal:

web_server:

status_led:
  pin: GPIO4

secplus_gdo:
  id:  ${id_prefix}
  input_gdo_pin: ${uart_rx_pin}
  output_gdo_pin: ${uart_tx_pin}

light:
  - platform: secplus_gdo
    name: Garage Door Light
    secplus_gdo_id: grgdo
    id: gdo_light

cover:
  - platform: secplus_gdo
    name: Garage Door
    secplus_gdo_id: grgdo
    id: gdo_door

text_sensor:
  - platform: version
    name: ESPHome Version
    hide_timestamp: true

sensor:
  - platform: secplus_gdo
    secplus_gdo_id: ${id_prefix}
    id: gdo_openings
    type: openings
    name: "Garage Door Openings"
    unit_of_measurement: "openings"
    icon: mdi:open-in-app
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Strength"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""

# Vehicle ToF Sensor - Required when TOF_I2C_PINS defined
  # - platform: secplus_gdo
  #   secplus_gdo_id: ${id_prefix}
  #   id: gdo_tof_distance
  #   type: tof_distance
#    name: "Vehicle Measured Distance" # Can be left commented to avoid cluttering the UI
  #   unit_of_measurement: "cm"
  #   internal: true
  #   filters:
  #     - heartbeat: 250ms
  #     - throttle: 1s

  # - platform: copy
  #   source_id: gdo_tof_distance
  #   name: Vehicle Distance Measure Filtered
  #   filters:
  #     - quantile:           # remove outliers that are not in the 90th percentile
  #         window_size: 8
  #         send_every: 1
  #         quantile: 0.90
  #     - heartbeat: 2s

  # - platform: dht
  #   model: DHT22
  #   pin: GPIO3
  #   temperature:
  #     name: "Temperature"
  #     accuracy_decimals: 1
  #   humidity:
  #     name: "Humidity"
  #     accuracy_decimals: 1
  #   update_interval: 60s

lock:
  - platform: secplus_gdo
    id: gdo_lock_remotes
    secplus_gdo_id: ${id_prefix}
    name: "Lock remotes"

binary_sensor:
  - platform: secplus_gdo
    name: "Garage Motion Sensor"
    id: gdo_motion
    secplus_gdo_id: ${id_prefix}
    device_class: motion
    type: motion
  - platform: secplus_gdo
    name: "Garage Door Obstruction Sensor"
    id: gdo_obst
    secplus_gdo_id: ${id_prefix}
    device_class: problem
    type: obstruction
  - platform: secplus_gdo
    name: "Garage Door Motor"
    id: gdo_motor
    secplus_gdo_id: ${id_prefix}
    device_class: running
    type: motor
  - platform: secplus_gdo
    name: "Garage Button"
    id: gdo_button
    secplus_gdo_id: ${id_prefix}
    entity_category: diagnostic
    type: button
  - platform: secplus_gdo
    name: $garage_sync_name
    id: gdo_synced
    secplus_gdo_id: ${id_prefix}
    type: sync
    device_class: connectivity

# Vehicle ToF Sensor = Binary state outputs
  # - platform: secplus_gdo
  #   secplus_gdo_id: ${id_prefix}
  #   id: gdo_vehicle_parked
  #   type: vehicle_parked
  #   name: "Vehicle parked"
  # - platform: secplus_gdo
  #   secplus_gdo_id: ${id_prefix}
  #   id: gdo_vehicle_arriving
  #   type: vehicle_arriving
  #   name: "Vehicle arriving"
  # - platform: secplus_gdo
  #   secplus_gdo_id: ${id_prefix}
  #   id: gdo_vehicle_leaving
  #   type: vehicle_leaving
  #   name: "Vehicle leaving"


  - platform: gpio
    id: "${id_prefix}_dry_contact_open"
    pin:
      number: ${dry_contact_open_pin}  #  dry contact for opening door
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Dry contact open"
    entity_category: diagnostic
    on_press:
      - if:
          condition:
            binary_sensor.is_off: ${id_prefix}_dry_contact_close
          then:
            - cover.open: gdo_door
      # - lambda: |-
      #       gdo_update_door_state(GDO_DOOR_STATE_OPEN);

  - platform: gpio
    id: "${id_prefix}_dry_contact_close"
    pin:
      number: ${dry_contact_close_pin}  # dry contact for closing door
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Dry contact close"
    entity_category: diagnostic
    on_press:
      - if:
          condition:
            binary_sensor.is_off: ${id_prefix}_dry_contact_open
          then:
            - cover.close: gdo_door
      # - lambda: |-
      #       gdo_update_door_state(GDO_DOOR_STATE_CLOSED);
  - platform: gpio
    id: "${id_prefix}_dry_contact_light"
    pin:
      number: ${dry_contact_light_pin}  # dry contact for triggering light
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Dry contact light"
    entity_category: diagnostic
    on_press:
      then:
        - light.toggle: gdo_light
    disabled_by_default: false

switch:
  - platform: secplus_gdo
    id: gdo_learn
    type: learn
    secplus_gdo_id: ${id_prefix}
    name: Learn
    icon: mdi:plus-box
    entity_category: config

  - platform: secplus_gdo
    id: gdo_toggle_only
    type: toggle_only
    secplus_gdo_id: ${id_prefix}
    name: Toggle Only
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:plus-box

  # - platform: secplus_gdo
  #   id: gdo_obst_override
  #   type: obst_override
  #   secplus_gdo_id: grgdo
  #   name: Obstruction Override
  #   restore_mode: RESTORE_DEFAULT_OFF
  #   icon: mdi:plus-box

  - platform: secplus_gdo
    id: gdo_close_notification
    type: close_notification
    secplus_gdo_id: ${id_prefix}
    name: "Close Notification"
    restore_mode: RESTORE_DEFAULT_OFF
    icon: "mdi:bell-alert"

select:
  - platform: secplus_gdo
    id: gdo_protocol
    secplus_gdo_id: ${id_prefix}
    name: protocol
    icon: mdi:settings
    entity_category: config

number:
  - platform: secplus_gdo
    name: Opening duration
    secplus_gdo_id: ${id_prefix}
    entity_category: config
    id: gdo_open_duration
    type: open_duration
    unit_of_measurement: "ms"

  - platform: secplus_gdo
    name: Closing duration
    secplus_gdo_id: ${id_prefix}
    entity_category: config
    id: gdo_close_duration
    type: close_duration
    unit_of_measurement: "ms"

  - platform: secplus_gdo
    name: Client ID
    secplus_gdo_id: ${id_prefix}
    entity_category: config
    id: gdo_client_id
    type: client_id
    mode: box

  - platform: secplus_gdo
    name: Rolling Code
    secplus_gdo_id: ${id_prefix}
    entity_category: config
    id: gdo_rolling_code
    type: rolling_code
    mode: box

# Vehicle ToF Sensor - REQUIRED when TOF_I2C_PINS are defined
  # - platform: secplus_gdo
  #   name: "Vehicle Parked Threshold"
  #   secplus_gdo_id: ${id_prefix}
  #   entity_category: config
  #   id: gdo_vehicle_parked_threshold
  #   type: vehicle_parked_threshold
  #   mode: box
  #   unit_of_measurement: "cm"

  # - platform: secplus_gdo
  #   name: "Vehicle Parked Threshold Variance"
  #   secplus_gdo_id: ${id_prefix}
  #   entity_category: config
  #   id: gdo_vehicle_parked_threshold_variance
  #   type: vehicle_parked_threshold_variance
  #   mode: box
  #   unit_of_measurement: "cm"

  # Remidiates wall button brownouts by throttling TX activity
  # 350ms recommened on 880LM units
  - platform: secplus_gdo
    name: Min Command Interval
    secplus_gdo_id: ${id_prefix}
    entity_category: config
    id: gdo_min_command_interval
    type: min_command_interval
    mode: box
    unit_of_measurement: "ms"

  # Add Time to Close (TTC) control, 0s = disabled
  - platform: secplus_gdo
    name: Time to Close
    secplus_gdo_id: ${id_prefix}
    entity_category: config
    id: gdo_time_to_close
    type: time_to_close
    mode: box
    unit_of_measurement: "s"

button:
  - platform: restart
    name: Restart
    id: restart_button
    entity_category: config
  - platform: factory_reset
    name: Factory Reset
    entity_category: config
  - platform: template
    name: Reset door timings
    entity_category: config
    on_press:
      - number.set:
          id: gdo_open_duration
          value: 0
      - number.set:
          id: gdo_close_duration
          value: 0
      - button.press:
          id: restart_button
  - platform: template
    name: Re-sync
    entity_category: config
    on_press:
      - number.increment:
          id: gdo_client_id
      - button.press:
          id: restart_button
